apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: flask-app
spec:
  type: ClusterIP
  selector:
    app: flask-app
    svc: db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
